# Generated by Django 5.0.6 on 2024-07-24 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EndLinePackageQuality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("product", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("shift", models.CharField(max_length=10)),
                ("line", models.CharField(max_length=50)),
                ("lotNumber", models.CharField(max_length=50)),
                ("bestByDate", models.DateField()),
                ("verification", models.JSONField()),
                ("initials", models.CharField(max_length=100)),
                ("historyOfChange", models.JSONField()),
                ("additionalComments", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ProductionEndOfShiftCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.CharField(max_length=100)),
                ("shift", models.CharField(max_length=10)),
                ("date", models.DateField()),
                ("producedQuantity", models.IntegerField()),
                ("defectCount", models.IntegerField()),
                ("operatorInitials", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[("worker", "Worker"), ("supervisor", "Supervisor")],
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
