# Generated by Django 5.0.6 on 2024-08-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JarsLidsTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("lot_number", models.CharField(max_length=50)),
                ("num_cases_jars", models.IntegerField()),
                ("num_cases_lids", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SanitationChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("room", models.CharField(max_length=100)),
                ("notes", models.TextField()),
                ("hands_washed", models.CharField(max_length=3)),
                ("contamination", models.CharField(max_length=3)),
                ("hair_nets", models.CharField(max_length=3)),
                ("packaging_covered", models.CharField(max_length=3)),
                ("hands_required", models.CharField(max_length=3)),
                ("products_stored", models.CharField(max_length=3)),
                ("chemicals_stored", models.CharField(max_length=3)),
                ("soap_towel", models.CharField(max_length=3)),
                ("initials", models.CharField(max_length=100)),
            ],
        ),
    ]
